In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [2]:
x = np.ones(3)
print(x)

[1. 1. 1.]


## Q#2: Create y array with elements equal to 0.

In [3]:
y = np.zeros(3)
print(y)

[0. 0. 0.]


## Q#3: Add x and y arrays.

In [4]:
add = x+y
print(add)

[1. 1. 1.]


## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [5]:
print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)

1
(3,)
3
float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [6]:
w = np.array([[11, 12], [13, 14], [15, 16]])
print(w)

[[11 12]
 [13 14]
 [15 16]]


## Q#6: Create z array contains the numbers from 1 to 3.

In [7]:
z = np.array([1, 2, 3])
print(z)

[1 2 3]


## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [8]:
#reshaped z to match the dimensions of w
re = z.reshape(-1, 1)
newArray = np.hstack((re, w))
print(newArray)

[[ 1 11 12]
 [ 2 13 14]
 [ 3 15 16]]


## Q#8: Print all elements of "newArray" using the loop.

In [9]:
for i in newArray:
    for j in i:
        print(j)

1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [10]:
rev = newArray[::-1, ::-1]
print(rev)

[[16 15  3]
 [14 13  2]
 [12 11  1]]


## Q#10: Decrement all elements of "newArray" with 1.

In [11]:
dec = newArray - 1
print(dec)

[[ 0 10 11]
 [ 1 12 13]
 [ 2 14 15]]


## Q#11: Find smallest and biggest values in "newArray".

In [12]:
s = np.min(newArray)
m = np.max(newArray)
print(s, m)

1 16


## Q#12: Print the first row of "newArray" using indexing.

In [13]:
print(newArray[0])

[ 1 11 12]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [14]:
num = newArray[0, 2]
print(num, newArray)

12 [[ 1 11 12]
 [ 2 13 14]
 [ 3 15 16]]


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [15]:
num0 = newArray[0, 2]
num13 = newArray[1, 1]

print(num0,num13, newArray)

12 13 [[ 1 11 12]
 [ 2 13 14]
 [ 3 15 16]]


## Q#15: Change the shape of "newArray" to (9,1).

In [16]:
re9 = newArray.reshape(9, 1)
print(re9)

[[ 1]
 [11]
 [12]
 [ 2]
 [13]
 [14]
 [ 3]
 [15]
 [16]]


## Q#16: Change the shape of "newArray" to (3,2).

In [17]:
re3= newArray.reshape(3, 2)
print(re3)

ValueError: cannot reshape array of size 9 into shape (3,2)

In [ ]:
"""
We cant reshape to (3.2) because it requires 6 items 
and in newArray we have 9 items but we can reshape to (3.3)
"""
re4 = newArray.reshape(3, 3)
print(re4)


# Well Done 🎉